config/routes.rb
WizzmapV6::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'
  match '/test', to: 'static_pages#test'

  get "groups/index"

  get "profiles/show"

  devise_for :users

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout

  end

  resources :points

  resources :groups

  get 'feed', to: 'points#index', as: :feed
  
  get 'list', to: 'points#list'

  get 'search', to: 'points#search'

  root to: 'points#index'

  get '/:id', to: 'profiles#show', as: :id 

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def help
  end

  def test
  end
end

app/views/static_pages/about.html.erb
<div class="row">
	<br />
	<h2 class="subheader">All About WizzMap</h2>
	<br />
	<h4 class="subheader">So what is WizzMap?</h4>
	<p>
	Wizzmap is way to store and organize geographic locations (points on a map). These points can be independent of addresses and can be organized in to groups.
	</p>
	<br />
	<h4 class="subheader">Why Beta?</h4>
	<p>
		WizzMap is still a work in progress, if you have ideas or feedback, let us know via email.
	</p>
	<br />
	<h4 class="subheader">Contact Info?</h4>
	<p>
	Any questions or issues can be sent to <a href="mailto:wizzmap@gmail.com">wizzmap@gmail.com</a>
	
	</p>
	<br />
<div>

app/views/static_pages/help.html.erb
<div class="row">
	<br />
	<h2 class="subheader">Instructions and Help</h2>
	<br />
	<h4 class="subheader">Welcome to Wizzmap</h4>
	<p>
	WizzMap is a way to store and group geographic locations. 
	</p>
	<br />
	<h4 class="subheader">How do I add a location?</h4>
	<p>
	You first need to <%= link_to 'create an account', register_path %> and/or <%= link_to 'login.', login_path %><br />
	Then just click on "Add a location" from the home page. 
	</p>
	<br />
	<h4 class="subheader">Contact Info?</h4>
	<p>
	Any questions or issues can be sent to <a href="mailto:wizzmap@gmail.com">wizzmap@gmail.com</a>
	
	</p>
	<br />
<div>

app/views/static_pages/test.html.erb
<div class="row">
	<br />
	<h2>Testing Page</h2>
	<br />
	<%= link_to 'New Point', new_point_path, class: "button" %>
        <br />
        <%= link_to 'List of Points for Debug', list_path, class: "button" %>
        <%= link_to 'List of Groups for Debug', groups_path, class: "button" %>

    
         <div id="dataDisplay">
            <h3 class="subheader">Data</h3>
            - pending -


          </div>
<div>