config/routes.rb
WizzmapV6::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'
  match '/test', to: 'static_pages#test'

  get "groups/index"

  get "profiles/show"

  devise_for :users

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout

  end

  resources :points

  resources :groups

  get 'feed', to: 'points#index', as: :feed
  
  get 'list', to: 'points#list'

  get 'search', to: 'points#search'

  root to: 'points#index'

  get '/:id', to: 'profiles#show', as: :id 

end

app/models/point.rb
class Point < ActiveRecord::Base
  attr_accessible :content, :lat, :long, :name, :user_id, :group_ids

  belongs_to :user
  has_and_belongs_to_many :groups

  acts_as_gmappable :process_geocoding => false, :lat => "lat", :lng => "long"

  validates :content, presence: true,
  						length: { minimum: 2 }

  validates :user_id, presence: true

# For Search

  def self.search(search)
    search_condition = "%" + search + "%"
    find(:all, :conditions => ['name LIKE ? OR content LIKE ?', search_condition, search_condition])
  end

#marker
def gmaps4rails_marker_picture
  {
   "picture" => "/assets/post.png",
   :width => 48,
   :height => 42
 }
end



end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]
  before_filter :authorize, only: [:edit, :update]
  # GET /points
  # GET /points.json
 
  
  def index
    @points = Point.all
    @json = Point.all.to_gmaps4rails do |point, marker|
      marker.infowindow render_to_string(:partial => "/points/infowindow", :locals => { :point => point})
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @points }
    end
  end

  #def index
  #  @points = Point.all
  #  @json = Point.all.to_gmaps4rails
#
#    respond_to do |format|
#      format.html # index.html.erb
#      format.json { render json: @points }
#    end
#  end


  def list
    @points = Point.all
    

    respond_to do |format|
      format.html # list.html.erb
      format.json { render json: @points }
    end
  end



  # GET /points/1
  # GET /points/1.json
  def show
    @point = Point.find(params[:id])
    @groups = @point.groups.all

    @menu_point = true

    @json = @point.to_gmaps4rails do |point, marker|
      marker.infowindow render_to_string(:partial => "/points/infowindow", :locals => { :point => point})
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @point }

    end
  end



  # GET /points/new
  # GET /points/new.json
  # Map Add
  def new
    @point = Point.new
    @json = @point.to_gmaps4rails

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @point }
    end
  end



  # GET /points/1/edit
  def edit
    @point = Point.find(params[:id])


  end
  

  # POST /points
  # POST /points.json
  def create
    @point = current_user.points.new(params[:point])

    respond_to do |format|
      if @point.save
        format.html { redirect_to @point, notice: 'Point was successfully created.' }
        format.json { render json: @point, point: :created, location: @point }
      else
        format.html { render action: "new" }
        format.json { render json: @point.errors, point: :unprocessable_entity }
      end
    end
  end


  # PUT /points/1
  # PUT /points/1.json
  def update
    @point = current_user.points.find(params[:id])
    
    if params[:point] && params[:point].has_key?(:user_id)
      params[:point].delete(user_id)
    end

    respond_to do |format|
      if @point.update_attributes(params[:point])
        format.html { redirect_to @point, notice: 'Point was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @point.errors, point: :unprocessable_entity }
      end
    end
  end


  #Search
  def search
    @points = Point.search params[:search]


  end




  # DELETE /points/1
  # DELETE /points/1.json
  def destroy
    @point = Point.find(params[:id])
    @point.destroy

    respond_to do |format|
      format.html { redirect_to points_url }
      format.json { head :no_content }
    end
  end

private
  def authorize()

      s = Point.find(params[:id])

      if current_user.id == s.user.id
        
      else
          flash[:error] = "You must be owner to edit"
          redirect_to(:back)
      end
     end
end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/points/_form.html.erb
<br />
<%= simple_form_for(@point) do |f| %>
  <% if @point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@point.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
      <% @point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name, input_html: { class: 'input-large' } %>
  Description
  <%= f.text_area :content, :rows => "15" %>
  <div class="hide">
  <%= f.input :lat, input_html: { class: 'input-xlarge' }  %>
  <%= f.input :long, input_html: { class: 'input-xlarge' }  %>
  </div>
  <br />
  <%= f.association :groups, 
                    collection: current_user.groups,
                    as: :check_boxes, input_html: { class: 'input-xlarge' }  %>
  <br /><br />
 <div class="form-button">
  <%= f.button :submit, class: "button small" %> <br/>
  or &nbsp <%= link_to 'Cancel', @point %> 
 </div>
<% end %>

app/views/points/_infoboxscript.html.erb
 <% content_for :scripts do %>
  <script type="text/javascript" charset="utf-8">
     
     Gmaps.map.infobox = function(boxText) {
        return { content: boxText,
                  disableAutoPan: false,
                  maxWidth: 0,
                  pixelOffset: new google.maps.Size(-140, 0),
                  zIndex: null,
                  boxStyle: { opacity: 0.95,
                              width: "280px"},
                  closeBoxMargin: "10px 2px 2px 2px",
                  closeBoxURL: "http://www.google.com/intl/en_us/mapfiles/close.gif",
                  infoBoxClearance: new google.maps.Size(1, 1),
                  isHidden: false,
                  pane: "floatPane",
                  enableEventPropagation: false }};
    
  </script>
<% end %>

app/views/points/_infowindow.html.erb
<!-- Info Window Partial -->

<div id="info-inside">
    <div id="info-title">
        <%= point.name %>
    </div>
    <div id="info-content">
       <%= point.content %>
    </div>

    <div id="info-menu">
    	<% if user_signed_in? %>
    		<% if current_user.id == point.user_id %>
    			<%= link_to ' Edit ', edit_point_path(point), class: "button small" %>
    		
    		<% end %>
    	<% end %>
    </div>

</div>

app/views/points/_mobilemenu.html.erb
<!-- Partial for Mobile menu -->

<div class="menu_mobile">

        <!-- Action Call -->
        <div id="menu_action" class="mobmen">
            <button class="toggle button expand" id="butt_act" type="button">Actions</button>
        </div>

        <!-- Main Menu show? -->                  
        <div id="menu_main" class="mobmen"> 


            <!--  Edit or Add to Group -->
            <% if user_signed_in? %>
                <% if @menu_point %>
                    <% if current_user.id == @point.user_id  %>
                        <%= link_to "Edit this Location", edit_point_path(@point), class: "button expand" %>
                    <% else %>
                        <%= link_to "Add This to a Group", root_path, class: "button expand" %>
                    <% end %>
                <% end %>
                <% if @menu_group && current_user.id == @group.user_id %>
                    <%= link_to "Edit this Group", edit_group_path(@group), class: "button expand" %>
                <% end %>
            <% end %>


            <!--  Search -->
            <!-- <button class="toggle btn btn-block" id="butt_search" type="button">Search</button> -->

            
            <!-- My Locations -->
            <% if user_signed_in? %>
                <button class="toggle button expand" id="butt_add" type="button">Create a New Location</button>
                <%= link_to "My Locations and Profile", id_path(current_user.profile_name), class: "button expand" %>
            
            <% else %>
                <%= link_to "Log In", login_path, class: "button expand" %>
            <% end %>

<!--  Center on Me -->           
            
             <%= link_to 'Center on Me', root_path, class: "button expand" %>


<!-- Collapse -->
            <button class="toggle button expand" id="butt_clear" type="button">Collapse</button>
        </div>
 

<!-- sub Menu -->
<!-- Add Location -->
        <div id="menu_add" class="mobmen">
            <span id="add_lat"></span>
            <span id="add_long"></span> 
            <ul class="button-group even-2">
                <li><button class="toggle button secondary" id="butt_clear2" type="button">Clear</button></li>
                <li><%= link_to 'Add Location', new_point_path, class: "button" %></li>
            </ul>
        </div>

<!-- sub Menu -->
<!-- Search (currrently disabled)   -->        
        <div id="menu_search" class="mobmen">
            <%= render 'points/searchform' %>
            <button class="toggle button expand" type="button">Clear</button>
        </div> 

    </div>

      <% content_for :scripts do %>
        <script type="text/javascript" charset="utf-8">
            
            function centerCall(){
                var lat = Gmaps.map.map.getCenter().lat();
                  sessionStorage.setItem("storLat", lat);
                var lng = Gmaps.map.map.getCenter().lng();
                  sessionStorage.setItem("storLong", lng);
                $('#add_lat').html(lat);         
                $('#add_long').html(lng);
            };

            Gmaps.map.callback = function() {
                google.maps.event.addListener(Gmaps.map.serviceObject, 'center_changed', function() {
                    centerCall();
                    }); 
                
                Gmaps.map.addMarkers({Lat: 43.6659304,
                                        Lng: -79.4264023, 
                                        rich_marker: null, 
                                        marker_picture: "/images/tornado-2.png"
                       });
            
            }; 
            



      
             <%= render 'points/infoboxscript' %>
                    
        </script>
    <% end %>

app/views/points/_searchform.html.erb
<h3 class="subheader">Search</h3>

- Pending form - 

app/views/points/_secondarymobilemenu.html.erb
<!-- Secondary Partial for Mobile menu -->

<div class="menu_mobile">

        <!-- Action Call -->
        <div id="menu_action" class="mobmen">
            <button class="toggle button expand" id="butt_act" type="button">Actions</button>
        </div>

        <!-- Main Menu show? -->                  
        <div id="menu_main" class="mobmen"> 


            <!--  Edit or Add to Group -->
            <% if user_signed_in? %>
                <% if @menu_point %>
                    <% if current_user.id == @point.user_id  %>
                        <%= link_to "Edit this Location", edit_point_path(@point), class: "button expand" %>
                    <% else %>
                        <%= link_to "Add This to a Group", root_path, class: "button expand" %>
                    <% end %>
                <% end %>
                <% if @menu_group && current_user.id == @group.user_id %>
                    <%= link_to "Edit this Group", edit_group_path(@group), class: "button expand" %>
                <% end %>
            <% end %>


           
            <!-- My Locations -->
            <% if user_signed_in? %>
                <button class="toggle button expand" id="butt_add" type="button">Create a New Location</button>
                <%= link_to "My Locations and Profile", id_path(current_user.profile_name), class: "button expand" %>
            
            <% else %>
                <%= link_to "Log In", login_path, class: "button expand" %>
            <% end %>

<!--  Center on Me -->           
            
             <%= link_to 'Center on Me', root_path, class: "button expand" %>


<!-- Collapse -->
            <button class="toggle button expand" id="butt_clear" type="button">Collapse</button>
        </div>


<!-- sub Menu -->
<!-- Add Location -->
        <div id="menu_add" class="mobmen">
            <span id="add_lat"></span>
            <span id="add_long"></span> 
            <ul class="button-group even-2">
                <li><button class="toggle button secondary" id="butt_clear2" type="button">Clear</button></li>
                <li><%= link_to 'Add Location', new_point_path, class: "button" %></li>
            </ul>
        </div>


    </div>


        
  

app/views/points/edit.html.erb
<!-- Edit Point -->


<% if mobile_device? %>    <!-- Mobile -->
	
	<div class="mobile-container">
		<h4>Edit Location</h4>
	    <%= render 'form' %>
	    <hr>
		You can also delete the point if needed.<br/><br />
		<%= link_to 'Delete Point', @point, class: "button alert small" %> 
	</div>


<% else %>

<br />

<div class="row">
	<div class="large-5 columns">
		<h3>Edit Point</h3>

		<%= render 'form' %>
		<hr>
		You can also delete the point if needed.<br/><br />
		
		<%= link_to 'Delete Point', @point, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button small alert' %>
		
		
		
	</div>

</div>

<% end %>

app/views/points/index.html.erb
<!-- Home Page -->

<% if mobile_device? %>   <!-- Mobile -->
    
    <!-- Map Call -->
    <div id="cross">
      <%= image_tag 'cross.png' %>
    </div>
    <%= gmaps("map_options" => { :raw => "{styles: deskStyle}",   
                              "detect_location" => true, 
                              "center_latitude" => 43.8,
                              "center_longitude" => -80,
                              "center_on_user" => true, 
                              "auto_zoom" => false,
                              "zoom" => 14,
                              "class" => "gmaps4rails_mobilemap"},
                              "markers" => { "data" => @json,
                                              "options" => {"custom_infowindow_class" => "infobox"} }) %> 

   
    <%= render 'mobilemenu' %>



<% else %>  <!-- Desktop -->


    <div class="m-map">
            <%= gmaps("map_options" => { :raw => "{styles: deskStyle}", 
                                        "center_latitude" => 43.8,
                                        "center_longitude" => -80,
                                        "detect_location" => false, 
                                        "center_on_user" => true, 
                                        "auto_adjust" => false,
                                        "zoom" => 8},
                                        "markers" => { "data" => @json,
                                                       "options" => {"custom_infowindow_class" => "infobox"} }) %>  

    </div>

    <div class="m-side">
        
        <%#= render 'searchform' %>
        
        <br />
        <p>Welcome to the beta version of WizzMap.
        </p>
        <h3 class="subheader">Actions</h3>
        <p>Too add a new location to the map:
        <%= link_to 'New Point', new_point_path %></p>

        <p>Too create a group of collections:
        <%= link_to 'New Group', new_group_path %></p>
        
        <p>If you need help or want to know how all of this works:
        <%= link_to 'Instructions and Help', help_path %></p>
        
        
            
    </div>
    

   <%= render 'infoboxscript' %>
    
<% end %>

app/views/points/list.html.erb
<!-- List of all Points for dev and debugging purposes -->



<div class="row-fluid">
    <div class="span10 offset1">
        <h2>Data Points</h2>
        <table class="table table-bordered">
            <% @points.each do |point| %>
              <tr>
                <td><%= point.user.profile_name %></td>
                <td><%= point.name %></td>
                <td><%= point.content %></td>
                <td>
                    <% if @groups %>
                        <% @groups.each do |group| %>
                            <li><%= group.group_name %></li>
                        <% end %>
                    <% else %>
                    No Groups
                    <% end %>
                </td>           
                <td><%= point.lat %></td>
                <td><%= point.long %></td>
                <td>
                    <%= link_to 'Show', point %>
                    <%= link_to 'Edit', edit_point_path(point) %>
                    <%= link_to 'Destroy', point, method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
              </tr>
            <% end %>
        </table>
    <br />

    <%= link_to 'New Point', new_point_path, class: "btn btn-success" %>

    </div>
</div>

app/views/points/new.html.erb
<!-- New Point Creation -->

<% if mobile_device? %>    <!-- Mobile -->
<div class="mobile-container">

    <%= render 'form' %>
    <br />

</div>

    <% content_for :scripts do %>
        <script type="text/javascript" charset="utf-8">
            
            function popForm(){
                var retLat = sessionStorage.getItem("storLat");
                var retLong = sessionStorage.getItem("storLong");
                
                $('#point_lat').val(retLat);
                $('#point_long').val(retLong);
                };
            popForm();
               
        </script>
    <% end %>


<% else %>       <!-- Desktop -->


    <div class="m-map">
		<div>
			<%#= gmaps4rails(@json) %>
             <%= gmaps("map_options" => { 
                                "detect_location" => true, 
                                "center_on_user" => true,
                                "center_latitude" => 43.8,
                                "center_longitude" => -80, 
                                "zoom" => 7},
                                "markers" => { "data" => @json }) %>
		</div>
	</div>
	<div class="m-side">
        <br />
        <h3 class="subheader">Add a location</h3>
		<%= render 'form' %>
        <br />
        <br />
        <b>Instructions</b><br />
        Click on the map for the location and then populate the form.
	</div>


<% content_for :scripts do %>
	<script type="text/javascript" charset="utf-8">
		var markersArray = [];

		// Clear markers on click, place new one, update coords
		Gmaps.map.callback = function() {
			google.maps.event.addListener(Gmaps.map.serviceObject, 'click', function(event) {
				clearOverlays();
				placeMarker(event.latLng);
				updateFormLocation(event.latLng);
			});

		};

		// Update form attributes with given Coordinates
		function updateFormLocation(latLng) {
            $('#point_lat').val(latLng.lat());
            $('#point_long').val(latLng.lng());
            $('#location_attributes_gmaps_zoom').val(Gmaps.map.serviceObject.getZoom());
        }

        // Add a marker with an open infowindow
        function placeMarker(latLng) {
            var marker = new google.maps.Marker({
                position: latLng, 
                map: Gmaps.map.serviceObject,
                draggable: true
            });
            markersArray.push(marker);
            // Set and open infowindow
            var infowindow = new google.maps.InfoWindow({
                content: '<div class="popup"><h3>Great!</h3><p>Now drag me and adjust the zoom level.<br /> Populate the form to add content to the location.</p>'
            });
            infowindow.open(Gmaps.map.serviceObject,marker);
            // Listen to drag & drop
            google.maps.event.addListener(marker, 'dragend', function() {
                updateFormLocation(this.getPosition());
            });
        }

        // Removes the overlays from the map
        function clearOverlays() {
          if (markersArray) {
            for (var i = 0; i < markersArray.length; i++ ) {
              markersArray[i].setMap(null);
            }
          }
          markersArray.length = 0;
        }
		

	</script>
<% end %>


<% end %>

app/views/points/search.html.erb
<!-- Search Result page -->


 
    <div class="page-header">   
        <h1>Search Results</h1>  
    </div>

  
    <% if @points %>

        <table>
          
        <% @points.each do |point| %>
          <tr>
            <td><%= point.user.profile_name %></td>
            <td><%= point.name %></td>
            <td><%= point.content %></td>
            <td><%= point.lat %></td>
            <td><%= point.long %></td>
            <td><%= link_to 'Show', point %></td>
            <td><%= link_to 'Edit', edit_point_path(point) %></td>
            <td><%= link_to 'Destroy', point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </table>
    <% else %>
        No Results
    <% end %>
       
        

app/views/points/show.html.erb
<!-- Point - Show -->
<!-- One Location Show -->

<% if mobile_device? %> <!-- Mobile -->
  <div class="map-label">
  <%= @point.name %>
  </div>
  
  <!-- Custom map options for 1 location show -->
  

  <%= gmaps("map_options" => { :raw => "{styles: deskStyle}",
                                "detect_location" => false, 
                                "center_on_user" => false, 
                                "auto_zoom" => false,
                                "zoom" => 12,
                                "class" => "gmaps4rails_mobilemap"},
                                "markers" => { "data" => @json,
                                                "options" => {"custom_infowindow_class" => "infobox"} }) %>
 
  
  <%= render 'secondarymobilemenu' %>
  <%= render 'points/infoboxscript' %>

<% else %>        <!-- Desktop -->

    <div class="m-map">

      <!-- Custom map options for 1 location show -->
      <%= gmaps("map_options" => {  :raw => "{styles: deskStyle}",
                                    "detect_location" => true, 
                                    "center_on_user" => false, 
                                    "auto_zoom" => false,
                                    "zoom" => 14},
                                    "markers" => { "data" => @json,
                                                    "options" => {"custom_infowindow_class" => "infobox"} }) %>  

    </div>

    <div class="m-side">
      <br />
      <h3 class="subheader"><%= @point.name %></h3>

      <em>By: </em> <%= @point.user.profile_name %>
      <br />
      <p><%= @point.content %>
      </p>

     <br />
     <br />
     <h5 class="subheader">Member of</h5>
        <% if @groups %>
          <% @groups.each do |group| %>
            <li><%= link_to group.group_name, group %></li><br />
          <% end %>

        <% else %>
          No Groups
        <% end %>
        <br />
        
        <%= link_to 'Edit this Point ', edit_point_path(@point), class: "button small" %> 

      
    
    </div>
 
  
  <%= render 'points/infoboxscript' %>
<% end %>