config/routes.rb
WizzmapV6::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'
  match '/test', to: 'static_pages#test'

  get "groups/index"

  get "profiles/show"

  devise_for :users

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout

  end

  resources :points

  resources :groups

  get 'feed', to: 'points#index', as: :feed
  
  get 'list', to: 'points#list'

  get 'search', to: 'points#search'

  root to: 'points#index'

  get '/:id', to: 'profiles#show', as: :id 

end

app/views/layouts/_navbar.html.erb
<nav class="top-bar" data-options="is_hover:false">
  <ul class="title-area">

    <!-- Title Area -->
    <li class="name">
      <h1><%= link_to "Wizzmap (beta)", root_path %></h1>
    </li>
  </ul>

  <section class="top-bar-section">

    <!-- Left Nav Section -->
    <ul class="left">      
     
    </ul>

    <!-- Right Nav Section -->
    <ul class="right">
      <% if user_signed_in? %>
          <li><%= link_to current_user.profile_name, id_path(current_user.profile_name) %></li>
          <% unless mobile_device? %><li><%= link_to "Log Out", logout_path %></li><% end %>
      <% else %>
          <li><%= link_to "Log In", login_path %></li>
          <% unless mobile_device? %><li><%= link_to "Register", register_path %></li><% end %> 
      <% end %>
      
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wizzmap - Beta Version </title>
  
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>


<!-- Mobile stuff -->
 
  <meta name="viewport" content="initial-scale=1.0, width=device-width" />

</head>

<body>

	<%= render 'layouts/navbar'  %>

	<% if flash %>
		<% flash.each do |type, message| %>
			<div data-alert class="alert-box <%= flash_class type %>" >
				<%= message %><a href="#" class="close">&times;</a>
			</div>
		<% end %>		
	<% end %>
		 
		 
	<%= yield %>

	<%= yield :scripts %>  <!-- for gmaps -->




</body>
</html>